### PR TITLE
Add physor presentation

### PR DESCRIPTION
**Pull request by aprilnovak**
1. Added PHSYOR presentation
2. Added PHYSOR paper
3. Added all supporting figures and output exodus files

### CODE REVIEW

**Comment by aprilnovak** [comment]
@lindsayad, I show a link to the Okapi repo in the PHYSOR presentation, so if there's anything else that should be updated in anticipation of some traffic [maybe :)], like updating LICENSE files, etc. then let me know!

**Review by lindsayad — COMMENTED** [review]
The paper and presentation both look great.

I don't know if you want to add it in this PR, but since you brought it up, it looks like the README should be updated

**Comment by aprilnovak** [comment]
Good idea, I'll add that to this PR

**Review by lindsayad — APPROVED** [review]
👍

**Pull request merged**
